version: '3'

services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    user: 1000:1000
    restart: always
    volumes:
      - ./vw-data/:/data/
    ports:
      - 8080:80
    environment: 
      - SMTP_HOST= #smtp server THE GMAIL SMTP WORKS IF YOU USE AN 'APP PASSWORD'
      - SMTP_FROM= #email 
      - SMTP_PORT= #smtp port
      - SMTP_SECURITY= #force_ssl or starttls or off
      - SMTP_USERNAME= # email 
      - SMTP_PASSWORD= # email password
      - SIGNUPS_ALLOWED=false
      - SHOW_PASSWORD_HINT=true
      - ADMIN_TOKEN= #ARGON2 use $$ to string escape 

  vaultwarden-backup:
    image: bruceforce/vaultwarden-backup
    container_name: vaultwarden-backup
    restart: always
    volumes:
      - ./backup/:/backup/ # You can specifiy this to be anywhere on the machine or even a remote samba share
    volumes_from:
      - vaultwarden
    environment:
      - CRON_TIME=0 0 * * *
      - BACKUP_DIR=/backup
      - BACKUP_ON_START=true
      - TIMESTAMP=true
      - DELETE_AFTER=2
      - UID=1000
      - GID=1000